apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: microbank
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Microbank Application Workloads

  sourceRepos:
  - https://github.com/Rajaraman-Ramanathan/microbank-gitops.git

  destinations:
  - namespace: microbank-*
    server: https://microbank-dev-control-plane:6443

  # Workloads MUST NOT create cluster-scoped resources
  clusterResourceBlacklist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'