apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Microbank Platform Components

  sourceRepos:
  - https://github.com/Rajaraman-Ramanathan/microbank-gitops.git

  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc

  - namespace: '*'
    server: https://microbank-dev-control-plane:6443

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'