apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/Rajaraman-Ramanathan/microbank-gitops.git
    targetRevision: dev
    path: platform/networking/ingress/ingress-nginx/helm
    helm:
      releaseName: ingress-nginx
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://microbank-dev-control-plane:6443
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true