apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  sources:
  - repoURL: https://github.com/Rajaraman-Ramanathan/platform-gitops.git
    targetRevision: dev
    path: platform/networking/ingress-nginx/helm
    helm:
      releaseName: ingress-nginx
      valueFiles:
        - $values/environments/dev/ingress/ingress-nginx/values.yaml
  - repoURL: https://github.com/Rajaraman-Ramanathan/platform-gitops.git
    targetRevision: dev
    ref: values
  destination:
    name: microbank-dev-cluster
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true