apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: platform
  source:
    repoURL: https://github.com/Rajaraman-Ramanathan/microbank-gitops.git
    targetRevision: dev
    path: environments/dev/platform/networking/ingress
  destination:
    server: https://microbank-dev-control-plane:6443
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true