apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maildev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://github.com/Rajaraman-Ramanathan/platform-gitops.git
    targetRevision: dev
    path: platform/dev-tools/maildev
  destination:
    name: microbank-dev-cluster
    namespace: maildev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true