apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://github.com/Rajaraman-Ramanathan/microbank-gitops.git
    targetRevision: dev
    path: platform/shared-infra/database/postgres/helm
    helm:
      releaseName: postgres
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://microbank-dev-control-plane:6443
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true