serviceAccount:
  create: true
  name: rabbitmq-sa

auth:
  username: devuser
  password: devpassword
  erlangCookie: devcookie

replicaCount: 1

image:
  repository: rabbitmq
  tag: 4.3.0-management
  pullPolicy: IfNotPresent

persistence:
  enabled: false

podLabels:
  app.kubernetes.io/name: rabbitmq
  app.kubernetes.io/component: messaging
  app.kubernetes.io/part-of: microbank
  app.kubernetes.io/managed-by: argocd
  network-role: platform

resources:
  requests:
    cpu: 150m
    memory: 256Mi
  limits:
    memory: 512Mi

service:
  type: ClusterIP
  port: 5672
  managementPort: 15672

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault

metrics:
  enabled: true
  serviceMonitor:
    enabled: false