serviceAccount:
  create: true
  name: minio-sa

mode: standalone

replicas: 1

image:
  repository: quay.io/minio/minio
  tag: RELEASE.2024-12-18T13-15-44Z
  pullPolicy: IfNotPresent

rootUser: devminio
rootPassword: devminiopassword

persistence:
  enabled: false

podLabels:
  app.kubernetes.io/name: minio
  app.kubernetes.io/component: storage
  app.kubernetes.io/part-of: microbank
  app.kubernetes.io/managed-by: argocd
  network-role: platform

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

consoleService:
  type: ClusterIP
  port: 9001
  targetPort: 9001

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    memory: 512Mi

securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

tls:
  enabled: false

etcd:
  endpoints: []
  clientCert: ""
  clientCertKey: ""

podDisruptionBudget:
  enabled: false

ingress:
  enabled: false

consoleIngress:
  enabled: false

deploymentUpdate:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 100%

oidc:
  enabled: false

mountPath: "/export"

certsPath: /tmp/certs

trustedCertsSecret: ""

minioAPIPort: "9000"
minioConsolePort: "9001"

networkPolicy:
  enabled: false

metrics:
  serviceMonitor:
    enabled: false

probes:
  startupProbe:
    enabled: true
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30

  livenessProbe:
    enabled: true
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    enabled: true
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1