apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
type: Opaque
stringData:
  username: {{ .Values.auth.username }}
  password: {{ .Values.auth.password }}
  erlang-cookie: {{ .Values.auth.erlangCookie }}