keycloak:
  serviceAccount:
    create: true
    name: keycloak-sa
  
  replicas: 1

  image:
    repository: quay.io/keycloak/keycloak
    tag: "24.0.3"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP

  postgresql:
    enabled: false

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 2Gi

  extraEnv: |
    - name: KEYCLOAK_ADMIN
      valueFrom:
        secretKeyRef:
          name: keycloak-secret
          key: username
    - name: KEYCLOAK_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-secret
          key: password
    - name: KC_DB
      value: postgres
    - name: KC_DB_URL_HOST
      value: postgres-postgresql.postgres.svc.cluster.local
    - name: KC_DB_URL_DATABASE
      value: keycloakdb
    - name: KC_DB_USERNAME
      value: keycloakuser
    - name: KC_DB_PASSWORD
      value: keycloakpass

  startupProbe: |
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 30
    timeoutSeconds: 5
    failureThreshold: 60
    periodSeconds: 10

  livenessProbe: |
    httpGet:
      path: /health/live
      port: http
    initialDelaySeconds: 60
    timeoutSeconds: 6
    failureThreshold: 5
    periodSeconds: 15

  readinessProbe: |
    httpGet:
      path: /health/ready
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 5
    failureThreshold: 5
    periodSeconds: 10

  extraEnvFrom: |
    - configMapRef:
        name: keycloak-config

  podLabels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: microbank
    app.kubernetes.io/managed-by: argocd
    network-role: identity

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  pgchecker:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

  command:
    - "/opt/keycloak/bin/kc.sh"
  args:
    - "start-dev"
    - "--import-realm"

  extraVolumes: |
    - name: realm-config
      configMap:
        name: keycloak-realm-config

  extraVolumeMounts: |
    - name: realm-config
      mountPath: /opt/keycloak/data/import
      readOnly: true