postgresql:
  serviceAccount:
    create: true
    name: postgres-sa

  architecture: standalone

  auth:
    username: platformadmin
    password: devpostgrespass
    database: platform

  primary:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        memory: 1Gi
    podLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: microbank
      app.kubernetes.io/managed-by: argocd
      network-role: data
    containerSecurityContext:
      enabled: true
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    service:
      type: ClusterIP
    networkPolicy:
      enabled: false
    startupProbe:
      enabled: true
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 30
      periodSeconds: 10
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      timeoutSeconds: 5
      failureThreshold: 10
      periodSeconds: 10
    readinessProbe:
      enabled: true
      initialDelaySeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      periodSeconds: 10

  metrics:
    enabled: true