apiVersion: apps/v1
kind: Deployment
metadata:
  name: maildev
  labels:
    app.kubernetes.io/name: maildev
    app.kubernetes.io/component: smtp-server
    app.kubernetes.io/part-of: microbank-platform
    app.kubernetes.io/managed-by: argocd
    tier: platform
    network-role: platform
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: maildev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: maildev
        app.kubernetes.io/component: smtp-server
        app.kubernetes.io/part-of: microbank-platform
        app.kubernetes.io/managed-by: argocd
        network-role: platform
    spec:
      containers:
      - name: maildev
        image: maildev/maildev:2.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1025  # SMTP
        - containerPort: 1080  # Web UI
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 1080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 1080
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 5
