apiVersion: v1
kind: Service
metadata:
  name: maildev
  labels:
    app.kubernetes.io/name: maildev
    app.kubernetes.io/component: smtp-server
    app.kubernetes.io/part-of: microbank-platform
spec:
  selector:
    app.kubernetes.io/name: maildev
  ports:
  - name: smtp
    port: 1025
    targetPort: 1025
  - name: ui
    port: 1080
    targetPort: 1080
