apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microbank-platform-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rajaraman-Ramanathan/microbank-gitops.git
    targetRevision: dev
    path: argocd/applications/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true