ingress-nginx:
  controller:
    replicaCount: 1

    ingressClassResource:
      name: nginx
      enabled: true
      default: true

    service:
      type: LoadBalancer

    admissionWebhooks:
      enabled: true

    metrics:
      enabled: true

  defaultBackend:
    enabled: true